// <auto-generated />
using System;
using ApiStoreWeb.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiStoreWeb.Migrations
{
    [DbContext(typeof(SmartphoneContext))]
    [Migration("20220309180926_Smartphone")]
    partial class Smartphone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiStoreWeb.Models.Entites.Purchase", b =>
                {
                    b.Property<int>("IdPurchase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("dayPurchase")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("valuePurchase")
                        .HasColumnType("double");

                    b.HasKey("IdPurchase");

                    b.HasIndex("Id");

                    b.ToTable("purchase", (string)null);
                });

            modelBuilder.Entity("ApiStoreWeb.Models.Entites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ApiStoreWeb.Models.Smartphone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<string>("Capacity")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<double>("ImeiOne")
                        .HasColumnType("double");

                    b.Property<double>("ImeiTwo")
                        .HasColumnType("double");

                    b.Property<string>("Memory")
                        .HasColumnType("longtext");

                    b.Property<string>("modelDescription")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("smartphone", (string)null);
                });

            modelBuilder.Entity("ApiStoreWeb.Models.Entites.Purchase", b =>
                {
                    b.HasOne("ApiStoreWeb.Models.Smartphone", "smartphoneId")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("smartphoneId");
                });
#pragma warning restore 612, 618
        }
    }
}
